name: mirror-repos

on:
  workflow_dispatch:
  schedule:
    - cron: '42 2 * * *'

jobs:
  mirror:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false  
      matrix:
        source-org: ['leanix', 'leanix-public', 'cleanshelf']

    steps:
    - uses: actions/checkout@v4

    - name: Mirror ${{ matrix.source-org }}
      run: ./mirror.sh ${{ matrix.source-org }}
      env:
        TOKEN_FOR_GITHUB_COM: ${{ secrets.TOKEN_FOR_GITHUB_TOOLS_SAP }}
    
    - name: Send mirror fail message
      if: failure()
      uses: archive/github-actions-slack@v2.9.0
      with:
        slack-bot-user-oauth-access-token: ${{ secrets.SLACK_TOKEN }}
        slack-channel: "#team-hook-status"
        slack-text: |
          :sos: Failed to mirror GitHub org ${{ matrix.source-org }} to SAP GitHub.
          ${{ env.ACTION_URL }}
